package top.tangff.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.tangff.pojo.RoleAuthExample;
import top.tangff.pojo.RoleAuthKey;

public interface RoleAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    int countByExample(RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    int deleteByExample(RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    int deleteByPrimaryKey(RoleAuthKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    int insert(RoleAuthKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    int insertSelective(RoleAuthKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    List<RoleAuthKey> selectByExample(RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") RoleAuthKey record, @Param("example") RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    int updateByExample(@Param("record") RoleAuthKey record, @Param("example") RoleAuthExample example);
}