package top.tangff.pojo;

import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.use_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private String useId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.cid
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.created
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.updated
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.use_id
     *
     * @return the value of article.use_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public String getUseId() {
        return useId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.use_id
     *
     * @param useId the value for article.use_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setUseId(String useId) {
        this.useId = useId == null ? null : useId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.cid
     *
     * @return the value of article.cid
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.cid
     *
     * @param cid the value for article.cid
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.created
     *
     * @return the value of article.created
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.created
     *
     * @param created the value for article.created
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.updated
     *
     * @return the value of article.updated
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.updated
     *
     * @param updated the value for article.updated
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}