package top.tangff.pojo;

import java.io.Serializable;

public class Auth implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth.id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth.parent_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth.name
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth.code
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth.path
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth.is_parent
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private Boolean isParent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth.id
     *
     * @return the value of auth.id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth.id
     *
     * @param id the value for auth.id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth.parent_id
     *
     * @return the value of auth.parent_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth.parent_id
     *
     * @param parentId the value for auth.parent_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth.name
     *
     * @return the value of auth.name
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth.name
     *
     * @param name the value for auth.name
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth.code
     *
     * @return the value of auth.code
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth.code
     *
     * @param code the value for auth.code
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth.path
     *
     * @return the value of auth.path
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth.path
     *
     * @param path the value for auth.path
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth.is_parent
     *
     * @return the value of auth.is_parent
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public Boolean getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth.is_parent
     *
     * @param isParent the value for auth.is_parent
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setIsParent(Boolean isParent) {
        this.isParent = isParent;
    }
}