package top.tangff.pojo;

import java.io.Serializable;
import java.util.Date;

public class Comment implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.use_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private String useId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.art_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private Long artId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.created
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.use_id
     *
     * @return the value of comment.use_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public String getUseId() {
        return useId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.use_id
     *
     * @param useId the value for comment.use_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setUseId(String useId) {
        this.useId = useId == null ? null : useId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.art_id
     *
     * @return the value of comment.art_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public Long getArtId() {
        return artId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.art_id
     *
     * @param artId the value for comment.art_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setArtId(Long artId) {
        this.artId = artId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.created
     *
     * @return the value of comment.created
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.created
     *
     * @param created the value for comment.created
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}