package top.tangff.pojo;

import java.io.Serializable;
import java.util.Date;

public class Reply implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.com_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private Long comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.parent_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.created
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.content
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.id
     *
     * @return the value of reply.id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.id
     *
     * @param id the value for reply.id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.com_id
     *
     * @return the value of reply.com_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public Long getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.com_id
     *
     * @param comId the value for reply.com_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setComId(Long comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.parent_id
     *
     * @return the value of reply.parent_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.parent_id
     *
     * @param parentId the value for reply.parent_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.created
     *
     * @return the value of reply.created
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.created
     *
     * @param created the value for reply.created
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.content
     *
     * @return the value of reply.content
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.content
     *
     * @param content the value for reply.content
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}