package top.tangff.pojo;

import java.io.Serializable;

public class RoleAuthKey implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_auth.id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_auth.rol_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private Long rolId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_auth.id
     *
     * @return the value of role_auth.id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_auth.id
     *
     * @param id the value for role_auth.id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_auth.rol_id
     *
     * @return the value of role_auth.rol_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public Long getRolId() {
        return rolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_auth.rol_id
     *
     * @param rolId the value for role_auth.rol_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setRolId(Long rolId) {
        this.rolId = rolId;
    }
}