package top.tangff.pojo;

public class UserRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.rol_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    private Long rolId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.id
     *
     * @return the value of user_role.id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.id
     *
     * @param id the value for user_role.id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.rol_id
     *
     * @return the value of user_role.rol_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public Long getRolId() {
        return rolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.rol_id
     *
     * @param rolId the value for user_role.rol_id
     *
     * @mbggenerated Thu Jun 07 21:37:41 CST 2018
     */
    public void setRolId(Long rolId) {
        this.rolId = rolId;
    }
}